spring:
  application:
    name: iot-device-listener
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 192.168.159.11
        port: 8848
  rabbitmq:
    password: admin
    username: admin
    host: 192.168.159.11
    port: 5672
server:
  port: 9004