spring:
  application:
    name: api-auth-gateway
#    redis配置

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 30000
  cloud:

    nacos:
      discovery:
        server-addr: 192.168.159.11:8848
        username: nacos
        password: nacos
#    gateway:
#      #gateway 路由
#      routes:
#
#        - id: user_op_route #路由 唯一标识
#          uri: lb://data-operation #使用nacos 的写法
#          predicates:       #断言
#            - Path=/data-serv/** #用户数据处理 会由PAth和一些固定字符组成类名
#          filters:
#            - StripPrefix=1 #提示省略第一层请求  就是data-serv
#        - id: device_op_route #路由 唯一标识
#          uri: lb://device-operation #使用nacos 的写法设备相关请求
#          predicates: #断言
#            - Path=/device-serv/** #设备数据处理 会由PAth和一些固定字符组成类名
#          filters:
#            - StripPrefix=1 #提示省略第一层请求  就是data-serv
#
#    sentinel:
#      transport:
#        dashboard: 192.168.159.11:8080
server:
  port: 7777
