server:
  port: 8888
spring:
  application:
    name: data-operation
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/iot-ydh?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: aaaaaa
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.159.11:8848
        username: nacos
        password: nacos
        namespace: public
#  邮件配置

  mail:
    host: smtp.163.com
#    password: Shaoyadong1
    password: GEZCSZHQYAZYZURB
    username: ydh_iot_now_start@163.com
    #port: 端口号
    default-encoding: UTF-8
    properties:
      mail.smtp.socketFactory.fallback: true
      mail.smtp.starttls.enable: true
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/email/
    suffix: .html
    cache: false
#mybatis-plus:
#  global-config:
#    db-config:
#      table-prefix: iot_
#日志开启
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

